/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class orm_ndkdemo_JniTest */

#ifndef _Included_orm_ndkdemo_JniTest
#define _Included_orm_ndkdemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     orm_ndkdemo_JniTest
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_orm_ndkdemo_JniTest_getCString
  (JNIEnv *, jclass);

/*
 * Class:     orm_ndkdemo_JniTest
 * Method:    calAAndB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_orm_ndkdemo_JniTest_calAAndB
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
